name: 报告误杀
description: "我发现了 被误杀/不应被拦截 的域名"
title: "[误杀]"
labels: ["bug", "误杀"]
body:
  - type: checkboxes
    attributes:
      label: 注意事项
      description: 请检查勾选以下事项，无效 issue 可能被关闭
      options:
        - label: 我做了简单验证，确定问题由 anti-AD 规则造成
          required: false
        - label: 我近期更新过 anti-AD 规则，当前版本仍存在问题
          required: false
        - label: 我将提供清晰明确的问题描述
          required: true

  - type: dropdown
    attributes:
      label: 使用的规则
      description: 请选择你使用的 anti-AD 规则类型
      options:
        - 请选择
        - anti-ad-adguard.txt
        - anti-ad-clash.yaml
        - anti-ad-dnsmasq.conf
        - anti-ad-domains.txt
        - anti-ad-easylist.txt
        - anti-ad-mihomo.mrs
        - anti-ad-sing-box.srs
        - anti-ad-smartdns.conf
        - anti-ad-surge.txt
        - anti-ad-surge2.txt
        - 其他（请在描述中说明）
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 使用的拦截工具
      description: 请选择你使用的拦截工具
      options:
        - 请选择
        - AdGuard
        - AdGuardHome
        - Clash/Meta/Mihomo
        - dnsmasq
        - Pi-Hole
        - Quantumult X
        - sing-box
        - SmartDNS
        - Surge
        - uBlock Origin
        - 其他
    validations:
      required: true

  - type: input
    attributes:
      label: 误杀域名
      description: 请提供不应被拦截的域名（列表）
      placeholder: abc.example.com / 我不清楚
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 请说明该域名被拦截后的影响，尽可能准确清晰
      value: |
          1. 问题发生时间：

          2. 涉及的平台/软件/功能：

          3. 误杀造成的影响：

          4. 截图、附件等（如有）：
    validations:
      required: true

